---
# Provision Openstack Instances
- import_playbook: provision-instances.yml

# Pre-Install Steps
- import_playbook: pre-install.yml

# Install
- import_playbook: install.yml

# Post Install
- import_playbook: post-install.yml
