---
- hosts: cluster_hosts
  roles:
    - role: sync-keys
      key_url: "{{ openshift_authorized_key_url | default('') }}"

- hosts: masters
  roles:
  - { role: create_users }

- import_playbook: ../../galaxy/openshift-applier/playbooks/openshift-cluster-seed.yml
  when:
  - openshift_cluster_content is defined
