---

###############################
# OpenShift Pre-Requisites

# Ensure the 'docker_storage_block_device' is correctly populated for all nodes
- hosts: nodes
  tasks:
    - set_fact:
        docker_storage_block_device: "{{ hostvars['localhost'].docker_storage_block_device }}"

# - subscribe hosts
# - prepare docker
# - other prep (install additional packages, etc.)
#
- hosts: OSEv3
  roles:
    - { role: ../../galaxy/openshift-ansible-contrib/roles/subscription-manager, when: hostvars.localhost.rhsm_register, tags: 'subscription-manager', ansible_sudo: true }
    - { role: ../../galaxy/openshift-ansible-contrib/roles/docker, tags: 'docker' }
    - { role: ../../galaxy/openshift-ansible-contrib/roles/openshift-prep, tags: 'openshift-prep' }

# Ensure the CNS / glusterFS facts are correctly populated for all CNS nodes
- hosts: glusterfs
  tasks:
    - set_fact:
       glusterfs_devices:
         - "{{ hostvars['localhost'].cns_node_glusterfs_volume }}"

