---

# Provision Openstack Instances
- import_playbook: openstack/provision.yml
  when: hosting_infrastructure == "openstack"

# Provision Openstack Instances
- import_playbook: aws/provision.yml
  when: hosting_infrastructure == "aws"
