---
- hosts: localhost
  pre_tasks:
  - include: roles/common/pre_tasks/pre_tasks.yml
  roles:
  - role: openstack-stack
    stack_name: "{{ env_id }}.{{ openstack_dns_domain }}"
    dns_domain: "{{ openstack_dns_domain }}"
    dns_nameservers: "{{ openstack_nameservers }}"
    subnet_prefix: "{{ openstack_subnet_prefix }}"
    ssh_public_key: "{{ openstack_ssh_public_key }}"
    openstack_image: "{{ openstack_default_image_name }}"
    etcd_flavor: "{{ openstack_default_flavor }}"
    master_flavor: "{{ openstack_default_flavor }}"
    node_flavor: "{{ openstack_default_flavor }}"
    infra_flavor: "{{ openstack_default_flavor }}"
    dns_flavor: "{{ openstack_dns_flavor | default('m1.small') }}"
    external_network: "{{ openstack_external_network_name }}"
    num_etcd: 0
    num_masters: 1
    num_nodes: "{{ openstack_num_nodes }}"
    num_infra: "{{ openstack_num_infra }}"
    num_dns: 1
    master_volume_size: "{{ docker_volume_size }}"
    app_volume_size: "{{ docker_volume_size }}"
    infra_volume_size: "{{ docker_volume_size }}"


- name: Refresh Server inventory
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - meta: refresh_inventory

- hosts: cluster_hosts
  gather_facts: false
  tasks:
  - name: Debug hostvar
    debug:
      msg: "{{ hostvars[inventory_hostname] }}"
      verbosity: 2
  - name: waiting for server to come back
    local_action: wait_for host={{ hostvars[inventory_hostname]['ansible_ssh_host'] }} port=22 delay=30 timeout=300
    become: false
