---

# 'hosting_infrastructure' is used to drive the correct behavior based
# on the hosting infrastructure, cloud provider, etc. Valid values are:
# - 'openstack'
# - 'aws'
# - 'azure' (Coming Soon)
# - 'gcp'
hosting_infrastructure: gcp

# Cluster Environment ID to uniquely identify the environment
env_id: env1

ansible_user: <your ssh key user>
ansible_become: true

dns_domain: "<REPLACE WITH A VALID ROUTE53 DNS DOMAIN>"

cloud_infrastructure:
   region: us-central1
   image_name: rhel7
   masters: 
     count: 3
     flavor: n1-standard-8
     zones: 
     - us-central1-a
     - us-central1-b
     - us-central1-f
     name_prefix: master
     preemptible: false
     docker_volume_size: 12
   appnodes: 
     count: 3
     flavor: n1-standard-4
     zones: 
     - us-central1-a
     - us-central1-b
     - us-central1-f
     name_prefix: node
     preemptible: false
     docker_volume_size: 50
   infranodes: 
     count: 3
     flavor: n1-standard-4
     zones: 
     - us-central1-a
     - us-central1-b
     - us-central1-f
     name_prefix: infranode          
     preemptible: false
     docker_volume_size: 20

# docker_storage_block_device: "/dev/vdb"

# Subscription Management Details
rhsm_register: True
rhsm_repos:
 - "rhel-7-server-rpms"
 - "rhel-7-server-ose-3.7-rpms"
 - "rhel-7-server-extras-rpms"
 - "rhel-7-fast-datapath-rpms"
 - "rhel-server-rhscl-7-rpms"


# Use RHSM username, password and optionally pool:
# NOTE: use the -e option to specify on CLI instead of statically set here
rhsm_username: '<REPLACE WITH VALID RHSM USERNAME>'
rhsm_password: '<REPLACE WITH VALID RHSM PASSWORD>'

# leave commented out if you want to `--auto-attach` a pool
#rhsm_pool: ''

# Specify the version of docker to use
docker_version: "1.12.*"

#google specific properties
service_account_email: <your google service account>
credentials_file: <your account key file in json format>
project_id: <your project>

# google object storage bucket name for the registry
# suggested value: openshift-registry-{{ env_id }}-{{ project_id }}
google_registry_bucket_name: openshift-registry-{{ env_id }}-{{ project_id }}

# openshift_master_cluster_public_hostname must be something like:
#   <prefix>.{{ env_id }}.{{ dns_domain }}
openshift_master_cluster_public_hostname: master.{{ env_id }}.{{ dns_domain }}

# openshift_master_cluster_hostname must be something like:
#   <prefix>.{{ env_id }}.{{ dns_domain }}
openshift_master_cluster_hostname: master-internal.{{ env_id }}.{{ dns_domain }}

# openshift_master_default_subdomain must be something like:
#   <prefix>.{{ env_id }}.{{ dns_domain }}
openshift_master_default_subdomain: apps.{{ env_id }}.{{ dns_domain }}
