---

# 'hosting_infrastructure' is used to drive the correct behavior based
# on the hosting infrastructure, cloud provider, etc. Valid values are:
# - 'openstack'
# - 'aws'
# - 'azure'
# - 'gcp'
hosting_infrastructure: openstack

# OpenStack Provisioning Variables
# use the "-e" option to set "openstack_ssh_public_key"
#openstack_ssh_public_key:

# Image name to be used with the instance provisioning
openstack_default_image_name: "<REPLACE WITH A VALID RHEL IMAGE NAME>"

# Default instance flavor (i.e.: instance size) for the provisioned instances
openstack_default_flavor: "m1.medium"

# Override the default above with specific flabors
#openstack_master_flavor: "m1.xlarge"
#openstack_lb_flavor: "m1.small"
#openstack_etcd_flavor: "m1.large"
#openstack_node_flavor: "m1.xlarge"
#openstack_infra_flavor: "m1.xlargse"

# The name of the network providing external access for the OpenStack tenant
openstack_external_network_name: "external"

# Subnet Prefix to be used within the OpenStack Tenant network
openstack_subnet_prefix: 192.168.99

# Number of master instances to deploy.
# This is a non-HA sample nventory so don't change this value
openstack_num_masters: 1

# Number of instances to be used as compute/app nodes
openstack_num_nodes: 2

# Number of instances to be used as infra nodes.
# This is a non-HA sample inventory so don't change this value
openstack_num_infra: 1

# Cluster Environment ID to uniquely identify the environment
env_id: "<REPLACE WITH VALID ENV ID - i.e: env1>"

# Change default ports to use standard 443
openshift_master_api_port: 443
openshift_master_console_port: 443

# DNS configurations
# The 'dns_domain' will be used as the base domain for the deployment
# The 'dns_nameservers' is a list of DNS resolvers the cluster should use
# - Note that the resolvers need to be able to resolve the "private/internal" IPs of the hosts.
#   This is often the same IP as the 'server' listed for the 'private' nsupdate section below.
dns_domain: "<REPLACE WITH A VALID DNS DOMAIN>"
dns_nameservers:
- <REPLACE WITH THE IP OF THE 'private' DNS SERVER BELOW>

# Sample configuration for the use of DNS servers for name resolution
# NOTE: The view names of `private` and `public` are REQUIRED as it indicates
#       the role each of these entries have.
#       Each view section can have multiple servers (i.e.: it's a list of servers)
nsupdate_config:
  - view: "private"
    zone: '<REPLACE WITH THE PRIVATE DNS SERVER ZONE NAME>'
    server_list:
      - key_secret: '<REPLACE WITH THE PRIVATE DNS SERVER KEY SECRET>'
        key_algorithm: '<REPLACE WITH THE PRIVATE DNS SERVER KEY ALGORITHM>'
        key_name: '<REPLACE WITH THE PRIVATE DNS SERVER KEY NAME>'
        server: '<REPLACE WITH THE PRIVATE DNS SERVER IP>'
  - view: "public"
    zone: '<REPLACE WITH THE PUBLIC DNS SERVER ZONE NAME>'
    server_list:
      - key_secret: '<REPLACE WITH THE PUBLIC DNS SERVER KEY SECRET>'
        key_algorithm: '<REPLACE WITH THE PUBLIC DNS SERVER KEY ALGORITHM>'
        key_name: '<REPLACE WITH THE PUBLIC DNS SERVER KEY NAME>'
        server: '<REPLACE WITH THE PUBLIC DNS SERVER IP>'

# Specify the version of docker to use
#docker_version: "1.12.*"

# Set this to false if you wish to use local storage, i.e.: not using an attached volume
#openshift_configure_container_storage: false

# Docker Storage configuration variables
docker_volume_size: "5"
docker_storage_block_device: "/dev/vdb"
docker_storage_mount_point: "/var/lib/containers/docker"


# Cinder Registry Storage - example 1
# - Auto provisioned Cinder registry storage variables
#   NOTE: the volume size must be specified in GiB, but WITHOUT the unit (i.e.: without "Gi")
#   Do NOT specify the `openshift_hosted_registry_storage_openstack_volumeID` variable for this scenario.
openshift_hosted_registry_storage_kind: openstack
#openshift_hosted_registry_storage_volume_size: 20

# Cinder Registry Storage - example 2
# - User provided Cinder registry storage variables
#   To leverage an existing Cinder volume already created
#   in OpenStack use the following variables.
#openshift_hosted_registry_storage_kind: openstack
#openshift_hosted_registry_storage_access_modes: ['ReadWriteOnce']
#openshift_hosted_registry_storage_openstack_filesystem: ext4
#openshift_hosted_registry_storage_openstack_volumeID: 3a650b4f-c8c5-4e0a-8ca5-eaee11f16c57
#openshift_hosted_registry_storage_volume_size: 20Gi
#openshift_hosted_registry_storage_annotations:
#- 'volume.beta.kubernetes.io/storage-class: standard'


# Subscription Management Details
rhsm_register: True
rhsm_repos:
  - "rhel-7-server-rpms"
  - "rhel-7-server-ose-3.11-rpms"
  - "rhel-7-server-extras-rpms"
  - "rhel-7-server-ansible-2.6-rpms"
  
# Keep this to use Red Hat Satellite:
rhsm_server_hostname: 'sat-6.example.com'
rhsm_org_id: 'CASL_ORG'
rhsm_activationkey: 'casl-latest'

# Uncomment the following to use RHSM username, password and optionally pool:
#rhsm_username: "{{ lookup('env', 'RHSM_USER' )}}"
#rhsm_password: "{{ lookup('env', 'RHSM_PASSWD' )}}"
# leave commented out if you want to `--auto-attach` a pool
#rhsm_pool: "{{ lookup('env', 'RHSM_POOL' )}}"

# WARNING: By default the tools will update RPMs during provisioning. If any packages are
# updated, the host(s) will reboot to ensure the correct versions are in use. This may
# NOT be desirable during an consecutive runs to just apply minor changes. If you would
# like to avoid "surprise" reboots, make sure to uncomment the following variable.
# Do NOTE that a reboot should most likely happen on initial install, so it's important
# that this variable is commented out or set to `True` for initial runs.
#update_cluster_hosts: False

# Uncomment the following `additional_list_of_packages_to_install` to list additional
# packages/RPMs to install during install
#additional_list_of_packages_to_install:
#  - rpm-1
#  - rpm-2
