---
- name: Validate OpenStack Variables
  fail: msg="Required OpenStack Variables not defined!"
  when: 
       - image_name is not defined or security_groups is not defined or key_name is not defined or image_name is not defined or flavor_name is not defined or env_id is not defined

# including both nova and neutron commands for compatibility and possible future decision making
- name: "Check for Security Groups"
  shell: "nova secgroup-list"
  #shell: "neutron security-group-list"
  with_items: security_groups.split(',')
  register: secgroup_list

- name: "Create Security Groups if required"
  shell: "nova secgroup-create {{ item.item }} {{ item.item }}"
  #shell: "neutron security-group-create {{ item.item }}"
  when: not item.stdout | search('{{ item.item }}')
  with_items: secgroup_list.results

- name: "Initialize SSH rule fact"
  set_fact:
    ssh_rule_found: false

- name: "Check for SSH rule in Security Groups"
  shell: "nova secgroup-list-rules {{ item }}"
  #shell: "neutron security-group-rule-list"
  with_items: security_groups.split(',')
  register: secgroup_rule_list

- name: "Set SSH rule fact on match"
  set_fact:
    ssh_rule_found: true
  when: item.stdout | search('tcp.*22.*22')
  #For Neutron - when: item.stdout| search('22/tcp')
  with_items: secgroup_rule_list.results

- name: "Create SSH Rule in first Security Group if required"
  shell: nova secgroup-add-rule {{ security_groups.split(',').0 }} tcp 22 22 0.0.0.0/0
  #shell: neutron security-group-rule-create --protocol tcp --port-range-min 22 --port-range-max 22 --direction ingress {{ security_groups.split(',').0 }}
  when: not ssh_rule_found

- name: "Search for valid OpenStack Flavor"
  shell: "nova flavor-list | awk \"/{{flavor_name }}/\"'{print $2}'"
  register: flavor_query

- name: Validate OpenStack Image
  fail: msg="Unable to determine a unique OpenStack Image"
  when: flavor_query.stdout.split()|length  != 1

- name: Setting OpenStack Image ID Fact
  set_fact:
    flavor_id: "{{ flavor_query.stdout }}"

- name: "Provision OpenStack {{ type }}"
  nova_compute:
    name: "{{ type }}{{ item }}-{{ env_id }}"
    state: present
    image_name: "{{ image_name }}"
    flavor_id: "{{ flavor_id }}"
    key_name: "{{ key_name }}"
    security_groups: "{{ security_groups }}"
    wait_for: 200
  with_sequence: "start=1 end={{ node_count | default(1) }}"
  register: "openstack_create"

- add_host:
    hostname: "{{ item.info.name }}"
    ansible_ssh_host: "{{ item.public_ip }}"
    ansible_ssh_user: root
    groups: "{{ register_host_group }}"
  with_items: openstack_create.results

- name: "Wait for {{ type }} to be available"
  wait_for: port=22 host={{ item.public_ip }}
  with_items: openstack_create.results
  
# Create Volumes
- include: create-volume.yml
  when: volume_size is defined and disk_volume is defined
  vars:
    instance_type: "{{ type }}"
    openstack_machines: "{{ openstack_create }}"
    storage_volume_size: "{{ volume_size }}"
    storage_disk_volume: "{{ disk_volume }}"
