---

# 'hosting_infrastructure' is used to drive the correct behavior based
# on the hosting infrastructure, cloud provider, etc. Valid values are:
# - 'openstack'
# - 'aws' (Coming Soon)
# - 'azure' (Coming Soon)
# - 'gcp'
hosting_infrastructure: openstack


# OpenStack Provisioning Variables
# use the "-e" option to set "openstack_ssh_public_key"
#openstack_ssh_public_key:
openstack_default_image_name: "rhel-guest-image-7.5-1.x86_64"
openstack_default_flavor: "m1.medium"
openstack_external_network_name: "external"
openstack_subnet_prefix: 192.168.99
openstack_num_masters: 3
openstack_num_nodes: 2
openstack_num_infra: 1

env_id: "s1-ha"

dns_domain: "casl.example.com"
dns_nameservers:
- 192.168.1.1

# Set this to false if you wish to use local storage, i.e.: not using an attached volume
#openshift_configure_container_storage: false

docker_volume_size: "10"
docker_storage_block_device: "/dev/vdb"
docker_storage_mount_point: "/var/lib/containers/docker"

# Subscription Management Details
rhsm_register: True
rhsm_repos:
  - "rhel-7-server-rpms"
  - "rhel-7-server-ose-3.11-rpms"
  - "rhel-7-server-extras-rpms"
  - "rhel-7-server-ansible-2.6-rpms"

# Keep this to use Red Hat Satellite:
rhsm_server_hostname: 'sat-6.example.com'
rhsm_org_id: 'CASL_ORG'
rhsm_activationkey: 'casl-latest'

# Uncomment the following to use RHSM username, password and optionally pool from environment variable:
#rhsm_username: "{{ lookup('env', 'RHSM_USER' )}}"
#rhsm_password: "{{ lookup('env', 'RHSM_PASSWD' )}}"
# leave commented out if you want to `--auto-attach` a pool
#rhsm_pool: "{{ lookup('env', 'RHSM_POOL' )}}"

# WARNING: By default the tools will update RPMs during provisioning. If any packages are
# updated, the host(s) will reboot to ensure the correct versions are in use. This may
# NOT be desirable during an consecutive runs to just apply minor changes. If you would
# like to avoid "surprise" reboots, make sure to uncomment the following variable.
# Do NOTE that a reboot should most likely happen on initial install, so it's important
# that this variable is commented out or set to `True` for initial runs.
#update_cluster_hosts: False

# Uncomment the following `additional_list_of_packages_to_install` to list additional
# packages/RPMs to install during install
#additional_list_of_packages_to_install:
#  - rpm-1
#  - rpm-2
