---

# Cluster Environment ID to uniquely identify the environment
env_id: c1-ocp

ansible_user: <your ssh key user>
ansible_become: true

dns_domain: "myorg.com"

# docker_storage_block_device: "/dev/vdb"
# docker_storage_mount_point: "/var/lib/containers/docker"

# Subscription Management Details
rhsm_register: True
rhsm_repos:
 - "rhel-7-server-rpms"
 - "rhel-7-server-ose-3.11-rpms"
 - "rhel-7-server-extras-rpms"
 - "rhel-7-server-ansible-2.6-rpms"


# Use RHSM username, password and optionally pool:
rhsm_username: "{{ lookup('env', 'RHSM_USER' )}}"
rhsm_password: "{{ lookup('env', 'RHSM_PASSWD' )}}"
# leave commented out if you want to `--auto-attach` a pool
rhsm_pool: "{{ lookup('env', 'RHSM_POOL' )}}"

# Uncomment this and comment out the above to use Red Hat Satellite:
#rhsm_server_hostname: 'sat-6.example.com'
#rhsm_org_id: 'CASL_ORG'
#rhsm_activationkey: 'casl-latest'

# Specify the version of docker to use
#docker_version: "1.12.*"
