---

- name: "Pull in Galaxy requirements - if set"
  include_tasks: install-dependencies.yml
  with_items:
  - "{{ openshift_cluster_content }}"
  loop_control:
    loop_var: dependencies
  when:
  - dependencies.galaxy_requirements is defined
  delegate_to: localhost

- name: "Copy inventory content to remote host(s) if not running 'locally'"
  import_tasks: copy-inventory-to-remote.yml
  when:
  - ansible_connection != 'local'

- name: "Create OpenShift objects"
  include_tasks: process-content.yml
  with_items:
  - "{{ openshift_cluster_content | filter_applier_items(filter_tags) | default([]) }}"
  loop_control:
    loop_var: entry
  when:
  - entry.content is defined or entry.content_dir is defined
