---

# We need to create namespaces and policies first,
# hence the special handling up front of these two...

- name: "Create OpenShift Cluster Namespaces"
  include: apply-content.yml
  with_items:
  - "{{ openshift_cluster_content }}"
  loop_control:
    loop_var: entry
  when:
  - entry.object == 'namespace'

- name: "Create OpenShift Cluster Policies"
  include: apply-content.yml
  with_items:
  - "{{ openshift_cluster_content }}"
  loop_control:
    loop_var: entry
  when:
  - entry.object == 'policy'

- name: "Create OpenShift cluster wide objects"
  include: apply-content.yml
  with_items:
  - "{{ openshift_cluster_content }}"
  loop_control:
    loop_var: entry
  when:
  - entry.object not in [ 'namespace', 'policy' ]

- name: "Create OpenShift objects with params"
  include: process-content.yml
  with_items:
  - "{{ openshift_cluster_content }}"
  loop_control:
    loop_var: entry
  when:
  - entry.object not in [ 'namespace', 'policy' ]
  - entry.content is defined 
